[profile.default]
src = 'contracts'
out = 'forge-artifacts'
# libs = ['lib']
libs = ['node_modules', 'lib']
test = 'tests/foundry'
cache_path = 'forge-cache'

# Pins the block number for the state fork
# fork_block_number = 16437883

# block_timestamp = 1651743369 # Arbitrary Thursday, 5 May 2022 09:36:09
verbosity = 3
solc_version = '0.7.6'

auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
cache = true
evm_version = 'london'
ffi = false
force = false
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = []
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
offline = false
optimizer = true
optimizer_runs = 200
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'

[profile.fuzz]
runs = 10000
